=== sstanovnik/ParallelTimetables/xml/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns="http://stanovnik.net/ParallelTimetables students.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://stanovnik.net/ParallelTimetables">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subjects">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:integer" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sstanovnik/ParallelTimetables/xml/handcoded/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns="http://stanovnik.net/ParallelTimetables"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://stanovnik.net/ParallelTimetables students.xsd">
    <student id="1">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
        </subjects>
    </student>
    <student id="2">
        <subjects>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
        </subjects>
    </student>
    <student id="3">
        <subjects>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
        </subjects>
    </student>
    <student id="4">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="5">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="6">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="7">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="8">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="9">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="10">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="11">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="12">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="13">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="14">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>5</id>
            <id>6</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
    <student id="15">
        <subjects>
            <id>1</id>
            <id>2</id>
            <id>3</id>
            <id>4</id>
            <id>7</id>
            <id>8</id>
            <id>9</id>
            <id>10</id>
        </subjects>
    </student>
</students>
